services:
  web:
    build:
      context: .
      target: runner
    image: ghcr.io/aidyn-tech/aidyn-landing:main
    environment:
      NODE_ENV: production
      PORT: "3000"
    depends_on:
      - reverse-proxy
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aidyn.rule=Host(`aidyn.localhost`)"
      - "traefik.http.routers.aidyn.entrypoints=web"
      - "traefik.http.services.aidyn.loadbalancer.server.port=3000"

  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  default:
    name: aidyn-network
